export const brands = [
  { id: 1, name: "Nishman", logo: "/logos/nishman.png" },
  { id: 2, name: "Snitch", logo: "/logos/snitch.png" },
  { id: 3, name: "Bewakoof", logo: "/logos/bewakoof.png" },
  { id: 4, name: "Sockscarving", logo: "/logos/sockscarving.png" },
  { id: 5, name: "Woggles", logo: "/logos/woggles.png" },
  { id: 6, name: "Sleven", logo: "/logos/sleven.png" },
  { id: 7, name: "Mago", logo: "/logos/mago.png" },
  { id: 8, name: "Planet Paaduks", logo: "/logos/planet-paaduks.png" },
  { id: 9, name: "Glitch Clothing", logo: "/logos/glitch.png" },
  { id: 10, name: "Bee & Beaver", logo: "/logos/bee-beaver.png" },
  { id: 11, name: "Bonjour Socks", logo: "/logos/bonjour.png" },
  { id: 12, name: "Magnet Club", logo: "/logos/magnet-club.png" },
  { id: 13, name: "Vige Perfumes", logo: "/logos/vige.png" },
  { id: 14, name: "See Designs", logo: "/logos/see-designs.png" },
  { id: 15, name: "Zaydn Sneakers", logo: "/logos/zaydn.png" },
  // { id: 16, name: "Citified", logo: "/logos/citified.png" },
  { id: 17, name: "Country House Cafe", logo: "/logos/country-house-cafe.png" },
];
